name: Music Generator

on: 

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Music Generator

      - name: Run a multi-line script
        run: |
          echo https://www.youtube.com/watch?v=dQw4w9WgXcQ
          echo POV: You got Rick-Rolled
